apiVersion: skaffold/v4beta5
kind: Config
metadata: 
  name: orion-messaging
build:
  googleCloudBuild:
    projectId: orion-messaging-388417
  artifacts:
    - image: us.gcr.io/orion-messaging-388417/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app/**/*/.ts'
            dest: .
          - src: app/**/*/.tsx'
            dest: .
    #- image: us.gcr.io/orion-messaging-388417/auth
      #context: auth
      #docker:
        #dockerfile: Dockerfile
      #sync:
        #manual:
          #- src: '**/*/.ts'
            #dest: .
    - image: us.gcr.io/orion-messaging-388417/connect
      context: connect
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*/.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*