export const dummyConversations = {
	conversations: [
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "Chat App Dev Team",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "superduperlongnamefortestinglet'skeep",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "a",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "b",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "c",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "d",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "e",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "f",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "g",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "h",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "i",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "j",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "k",
			type: "friend",
		},
	],
};
