export const dummyConversations = {
	conversations: [
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "radadada",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "dnadnaidnaidiandaidaidaindandai",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
		{
			conversationId: 1231,
			users: ["cat", "dog"],
			conversationImageUrl: "/dada/da",
			conversationName: "cat",
			type: "friend",
		},
	],
};
