apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.org/websocket-services: "message-srv"
spec:
  rules:
    - host: orion-messaging.com
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/connect/?(.*)
            pathType: Prefix
            backend:
              service:
                name: connect-srv
                port:
                  number: 3000
          - path: /socket/message-socket/?(.*)
            pathType: Prefix
            backend:
              service:
                name: message-srv
                port:
                  number: 8080
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
          